export var districts=[
    {state_id: 3, district_name: "Anjaw", district_id: 22},
    {state_id: 3, district_name: "Changlang", district_id: 20},
    {state_id: 3, district_name: "Dibang Valley", district_id: 25},
    {state_id: 3, district_name: "East Kameng", district_id: 23},
    {state_id: 3, district_name: "East Siang", district_id: 42},
    {state_id: 3, district_name: "Itanagar Capital Complex", district_id: 17},
    {state_id: 3, district_name: "Kamle", district_id: 24},
    {state_id: 3, district_name: "Kra Daadi", district_id: 27},
    {state_id: 3, district_name: "Kurung Kumey", district_id: 21},
    {state_id: 3, district_name: "Lepa Rada", district_id: 33},
    {state_id: 3, district_name: "Lohit", district_id: 29},
    {state_id: 3, district_name: "Longding", district_id: 40},
    {state_id: 3, district_name: "Lower Dibang Valley", district_id: 31},
    {state_id: 3, district_name: "Lower Siang", district_id: 18},
    {state_id: 3, district_name: "Lower Subansiri", district_id: 32},
    {state_id: 3, district_name: "Namsai", district_id: 36},
    {state_id: 3, district_name: "Pakke Kessang", district_id: 19},
    {state_id: 3, district_name: "Papum Pare", district_id: 39},
    {state_id: 3, district_name: "Shi Yomi", district_id: 35},
    {state_id: 3, district_name: "Siang", district_id: 37},
    {state_id: 3, district_name: "Tawang", district_id: 30},
    {state_id: 3, district_name: "Tirap", district_id: 26},
    {state_id: 3, district_name: "Upper Siang", district_id: 34},
    {state_id: 3, district_name: "Upper Subansiri", district_id: 41},
    {state_id: 3, district_name: "West Kameng", district_id: 28},
    {state_id: 3, district_name: "West Siang", district_id: 38},
    {state_id: 2, district_name: "Anantapur", district_id: 9},
    {state_id: 2, district_name: "Chittoor", district_id: 10},
    {state_id: 2, district_name: "East Godavari", district_id: 11},
    {state_id: 2, district_name: "Guntur", district_id: 5},
    {state_id: 2, district_name: "Krishna", district_id: 4},
    {state_id: 2, district_name: "Kurnool", district_id: 7},
    {state_id: 2, district_name: "Prakasam", district_id: 12},
    {state_id: 2, district_name: "Sri Potti Sriramulu Nellore", district_id: 13},
    {state_id: 2, district_name: "Srikakulam", district_id: 14},
    {state_id: 2, district_name: "Visakhapatnam", district_id: 8},
    {state_id: 2, district_name: "Vizianagaram", district_id: 15},
    {state_id: 2, district_name: "West Godavari", district_id: 16},
    {state_id: 2, district_name: "YSR District, Kadapa (Cuddapah)", district_id: 6},
    {state_id: 4, district_name: "Baksa", district_id: 46},
    {state_id: 4, district_name: "Barpeta", district_id: 47},
    {state_id: 4, district_name: "Biswanath", district_id: 765},
    {state_id: 4, district_name: "Bongaigaon", district_id: 57},
    {state_id: 4, district_name: "Cachar", district_id: 66},
    {state_id: 4, district_name: "Charaideo", district_id: 766},
    {state_id: 4, district_name: "Chirang", district_id: 58},
    {state_id: 4, district_name: "Darrang", district_id: 48},
    {state_id: 4, district_name: "Dhemaji", district_id: 62},
    {state_id: 4, district_name: "Dhubri", district_id: 59},
    {state_id: 4, district_name: "Dibrugarh", district_id: 43},
    {state_id: 4, district_name: "Dima Hasao", district_id: 67},
    {state_id: 4, district_name: "Goalpara", district_id: 60},
    {state_id: 4, district_name: "Golaghat", district_id: 53},
    {state_id: 4, district_name: "Hailakandi", district_id: 68},
    {state_id: 4, district_name: "Hojai", district_id: 764},
    {state_id: 4, district_name: "Jorhat", district_id: 54},
    {state_id: 4, district_name: "Kamrup Metropolitan", district_id: 49},
    {state_id: 4, district_name: "Kamrup Rural", district_id: 50},
    {state_id: 4, district_name: "Karbi-Anglong", district_id: 51},
    {state_id: 4, district_name: "Karimganj", district_id: 69},
    {state_id: 4, district_name: "Kokrajhar", district_id: 61},
    {state_id: 4, district_name: "Lakhimpur", district_id: 63},
    {state_id: 4, district_name: "Majuli", district_id: 767},
    {state_id: 4, district_name: "Morigaon", district_id: 55},
    {state_id: 4, district_name: "Nagaon", district_id: 56},
    {state_id: 4, district_name: "Nalbari", district_id: 52},
    {state_id: 4, district_name: "Sivasagar", district_id: 44},
    {state_id: 4, district_name: "Sonitpur", district_id: 64},
    {state_id: 4, district_name: "South Salmara Mankachar", district_id: 768},
    {state_id: 4, district_name: "Tinsukia", district_id: 45},
    {state_id: 4, district_name: "Udalguri", district_id: 65},
    {state_id: 4, district_name: "West Karbi Anglong", district_id: 769},
    {state_id: 10, district_name: "North Goa", district_id: 151},
    {state_id: 10, district_name: "South Goa", district_id: 152},
    {state_id: 1, district_name: "Nicobar", district_id: 3},
    {state_id: 1, district_name: "North and Middle Andaman", district_id: 1},
    {state_id: 1, district_name: "South Andaman", district_id: 2},
    {state_id: 7, district_name: "Balod", district_id: 110},
    {state_id: 7, district_name: "Baloda bazar", district_id: 111},
    {state_id: 7, district_name: "Balrampur", district_id: 112},
    {state_id: 7, district_name: "Bastar", district_id: 113},
    {state_id: 7, district_name: "Bemetara", district_id: 114},
    {state_id: 7, district_name: "Bijapur", district_id: 115},
    {state_id: 7, district_name: "Bilaspur", district_id: 116},
    {state_id: 7, district_name: "Dantewada", district_id: 117},
    {state_id: 7, district_name: "Dhamtari", district_id: 118},
    {state_id: 7, district_name: "Durg", district_id: 119},
    {state_id: 7, district_name: "Gariaband", district_id: 120},
    {state_id: 7, district_name: "Gaurela Pendra Marwahi ", district_id: 136},
    {state_id: 7, district_name: "Janjgir-Champa", district_id: 121},
    {state_id: 7, district_name: "Jashpur", district_id: 122},
    {state_id: 7, district_name: "Kanker", district_id: 123},
    {state_id: 7, district_name: "Kawardha", district_id: 135},
    {state_id: 7, district_name: "Kondagaon", district_id: 124},
    {state_id: 7, district_name: "Korba", district_id: 125},
    {state_id: 7, district_name: "Koriya", district_id: 126},
    {state_id: 7, district_name: "Mahasamund", district_id: 127},
    {state_id: 7, district_name: "Mungeli", district_id: 128},
    {state_id: 7, district_name: "Narayanpur", district_id: 129},
    {state_id: 7, district_name: "Raigarh", district_id: 130},
    {state_id: 7, district_name: "Raipur", district_id: 109},
    {state_id: 7, district_name: "Rajnandgaon", district_id: 131},
    {state_id: 7, district_name: "Sukma", district_id: 132},
    {state_id: 7, district_name: "Surajpur", district_id: 133},
    {state_id: 7, district_name: "Surguja", district_id: 134},
    {state_id: 9, district_name: "Central Delhi", district_id: 141},
    {state_id: 9, district_name: "East Delhi", district_id: 145},
    {state_id: 9, district_name: "New Delhi", district_id: 140},
    {state_id: 9, district_name: "North Delhi", district_id: 146},
    {state_id: 9, district_name: "North East Delhi", district_id: 147},
    {state_id: 9, district_name: "North West Delhi", district_id: 143},
    {state_id: 9, district_name: "Shahdara", district_id: 148},
    {state_id: 9, district_name: "South Delhi", district_id: 149},
    {state_id: 9, district_name: "South East Delhi", district_id: 144},
    {state_id: 9, district_name: "South West Delhi", district_id: 150},
    {state_id: 9, district_name: "West Delhi", district_id: 142},
    {state_id: 6, district_name: "Chandigarh", district_id: 108},
    {state_id: 8, district_name: "Dadra and Nagar Haveli", district_id: 137},
    {state_id: 5, district_name: "Araria", district_id: 74},
    {state_id: 5, district_name: "Arwal", district_id: 78},
    {state_id: 5, district_name: "Aurangabad", district_id: 77},
    {state_id: 5, district_name: "Banka", district_id: 83},
    {state_id: 5, district_name: "Begusarai", district_id: 98},
    {state_id: 5, district_name: "Bhagalpur", district_id: 82},
    {state_id: 5, district_name: "Bhojpur", district_id: 99},
    {state_id: 5, district_name: "Buxar", district_id: 100},
    {state_id: 5, district_name: "Darbhanga", district_id: 94},
    {state_id: 5, district_name: "East Champaran", district_id: 105},
    {state_id: 5, district_name: "Gaya", district_id: 79},
    {state_id: 5, district_name: "Gopalganj", district_id: 104},
    {state_id: 5, district_name: "Jamui", district_id: 107},
    {state_id: 5, district_name: "Jehanabad", district_id: 91},
    {state_id: 5, district_name: "Kaimur", district_id: 80},
    {state_id: 5, district_name: "Katihar", district_id: 75},
    {state_id: 5, district_name: "Khagaria", district_id: 101},
    {state_id: 5, district_name: "Kishanganj", district_id: 76},
    {state_id: 5, district_name: "Lakhisarai", district_id: 84},
    {state_id: 5, district_name: "Madhepura", district_id: 70},
    {state_id: 5, district_name: "Madhubani", district_id: 95},
    {state_id: 5, district_name: "Munger", district_id: 85},
    {state_id: 5, district_name: "Muzaffarpur", district_id: 86},
    {state_id: 5, district_name: "Nalanda", district_id: 90},
    {state_id: 5, district_name: "Nawada", district_id: 92},
    {state_id: 5, district_name: "Patna", district_id: 97},
    {state_id: 5, district_name: "Purnia", district_id: 73},
    {state_id: 5, district_name: "Rohtas", district_id: 81},
    {state_id: 5, district_name: "Saharsa", district_id: 71},
    {state_id: 5, district_name: "Samastipur", district_id: 96},
    {state_id: 5, district_name: "Saran", district_id: 102},
    {state_id: 5, district_name: "Sheikhpura", district_id: 93},
    {state_id: 5, district_name: "Sheohar", district_id: 87},
    {state_id: 5, district_name: "Sitamarhi", district_id: 88},
    {state_id: 5, district_name: "Siwan", district_id: 103},
    {state_id: 5, district_name: "Supaul", district_id: 72},
    {state_id: 5, district_name: "Vaishali", district_id: 89},
    {state_id: 5, district_name: "West Champaran", district_id: 106},
    {state_id: 37, district_name: "Daman", district_id: 138},
    {state_id: 37, district_name: "Diu", district_id: 139},
    {state_id: 15, district_name: "Bokaro", district_id: 242},
    {state_id: 15, district_name: "Chatra", district_id: 245},
    {state_id: 15, district_name: "Deoghar", district_id: 253},
    {state_id: 15, district_name: "Dhanbad", district_id: 257},
    {state_id: 15, district_name: "Dumka", district_id: 258},
    {state_id: 15, district_name: "East Singhbhum", district_id: 247},
    {state_id: 15, district_name: "Garhwa", district_id: 243},
    {state_id: 15, district_name: "Giridih", district_id: 256},
    {state_id: 15, district_name: "Godda", district_id: 262},
    {state_id: 15, district_name: "Gumla", district_id: 251},
    {state_id: 15, district_name: "Hazaribagh", district_id: 255},
    {state_id: 15, district_name: "Jamtara", district_id: 259},
    {state_id: 15, district_name: "Khunti", district_id: 252},
    {state_id: 15, district_name: "Koderma", district_id: 241},
    {state_id: 15, district_name: "Latehar", district_id: 244},
    {state_id: 15, district_name: "Lohardaga", district_id: 250},
    {state_id: 15, district_name: "Pakur", district_id: 261},
    {state_id: 15, district_name: "Palamu", district_id: 246},
    {state_id: 15, district_name: "Ramgarh", district_id: 254},
    {state_id: 15, district_name: "Ranchi", district_id: 240},
    {state_id: 15, district_name: "Sahebganj", district_id: 260},
    {state_id: 15, district_name: "Seraikela Kharsawan", district_id: 248},
    {state_id: 15, district_name: "Simdega", district_id: 249},
    {state_id: 15, district_name: "West Singhbhum", district_id: 263},
    {state_id: 12, district_name: "Ambala", district_id: 193},
    {state_id: 12, district_name: "Bhiwani", district_id: 200},
    {state_id: 12, district_name: "Charkhi Dadri", district_id: 201},
    {state_id: 12, district_name: "Faridabad", district_id: 199},
    {state_id: 12, district_name: "Fatehabad", district_id: 196},
    {state_id: 12, district_name: "Gurgaon", district_id: 188},
    {state_id: 12, district_name: "Hisar", district_id: 191},
    {state_id: 12, district_name: "Jhajjar", district_id: 189},
    {state_id: 12, district_name: "Jind", district_id: 204},
    {state_id: 12, district_name: "Kaithal", district_id: 190},
    {state_id: 12, district_name: "Karnal", district_id: 203},
    {state_id: 12, district_name: "Kurukshetra", district_id: 186},
    {state_id: 12, district_name: "Mahendragarh", district_id: 206},
    {state_id: 12, district_name: "Nuh", district_id: 205},
    {state_id: 12, district_name: "Palwal", district_id: 207},
    {state_id: 12, district_name: "Panchkula", district_id: 187},
    {state_id: 12, district_name: "Panipat", district_id: 195},
    {state_id: 12, district_name: "Rewari", district_id: 202},
    {state_id: 12, district_name: "Rohtak", district_id: 192},
    {state_id: 12, district_name: "Sirsa", district_id: 194},
    {state_id: 12, district_name: "Sonipat", district_id: 198},
    {state_id: 12, district_name: "Yamunanagar", district_id: 197},
    {state_id: 18, district_name: "Kargil", district_id: 309},
    {state_id: 18, district_name: "Leh", district_id: 310},
    {state_id: 11, district_name: "Ahmedabad", district_id: 154},
    {state_id: 11, district_name: "Ahmedabad Corporation", district_id: 770},
    {state_id: 11, district_name: "Amreli", district_id: 174},
    {state_id: 11, district_name: "Anand", district_id: 179},
    {state_id: 11, district_name: "Aravalli", district_id: 158},
    {state_id: 11, district_name: "Banaskantha", district_id: 159},
    {state_id: 11, district_name: "Bharuch", district_id: 180},
    {state_id: 11, district_name: "Bhavnagar", district_id: 175},
    {state_id: 11, district_name: "Bhavnagar Corporation", district_id: 771},
    {state_id: 11, district_name: "Botad", district_id: 176},
    {state_id: 11, district_name: "Chhotaudepur", district_id: 181},
    {state_id: 11, district_name: "Dahod", district_id: 182},
    {state_id: 11, district_name: "Dang", district_id: 163},
    {state_id: 11, district_name: "Devbhumi Dwaraka", district_id: 168},
    {state_id: 11, district_name: "Gandhinagar", district_id: 153},
    {state_id: 11, district_name: "Gandhinagar Corporation", district_id: 772},
    {state_id: 11, district_name: "Gir Somnath", district_id: 177},
    {state_id: 11, district_name: "Jamnagar", district_id: 169},
    {state_id: 11, district_name: "Jamnagar Corporation", district_id: 773},
    {state_id: 11, district_name: "Junagadh", district_id: 178},
    {state_id: 11, district_name: "Junagadh Corporation", district_id: 774},
    {state_id: 11, district_name: "Kheda", district_id: 156},
    {state_id: 11, district_name: "Kutch", district_id: 170},
    {state_id: 11, district_name: "Mahisagar", district_id: 183},
    {state_id: 11, district_name: "Mehsana", district_id: 160},
    {state_id: 11, district_name: "Morbi", district_id: 171},
    {state_id: 11, district_name: "Narmada", district_id: 184},
    {state_id: 11, district_name: "Navsari", district_id: 164},
    {state_id: 11, district_name: "Panchmahal", district_id: 185},
    {state_id: 11, district_name: "Patan", district_id: 161},
    {state_id: 11, district_name: "Porbandar", district_id: 172},
    {state_id: 11, district_name: "Rajkot", district_id: 173},
    {state_id: 11, district_name: "Rajkot Corporation", district_id: 775},
    {state_id: 11, district_name: "Sabarkantha", district_id: 162},
    {state_id: 11, district_name: "Surat", district_id: 165},
    {state_id: 11, district_name: "Surat Corporation", district_id: 776},
    {state_id: 11, district_name: "Surendranagar", district_id: 157},
    {state_id: 11, district_name: "Tapi", district_id: 166},
    {state_id: 11, district_name: "Vadodara", district_id: 155},
    {state_id: 11, district_name: "Vadodara Corporation", district_id: 777},
    {state_id: 11, district_name: "Valsad", district_id: 167},
    {state_id: 16, district_name: "Bagalkot", district_id: 270},
    {state_id: 16, district_name: "Bangalore Rural", district_id: 276},
    {state_id: 16, district_name: "Bangalore Urban", district_id: 265},
    {state_id: 16, district_name: "BBMP", district_id: 294},
    {state_id: 16, district_name: "Belgaum", district_id: 264},
    {state_id: 16, district_name: "Bellary", district_id: 274},
    {state_id: 16, district_name: "Bidar", district_id: 272},
    {state_id: 16, district_name: "Chamarajanagar", district_id: 271},
    {state_id: 16, district_name: "Chikamagalur", district_id: 273},
    {state_id: 16, district_name: "Chikkaballapur", district_id: 291},
    {state_id: 16, district_name: "Chitradurga", district_id: 268},
    {state_id: 16, district_name: "Dakshina Kannada", district_id: 269},
    {state_id: 16, district_name: "Davanagere", district_id: 275},
    {state_id: 16, district_name: "Dharwad", district_id: 278},
    {state_id: 16, district_name: "Gadag", district_id: 280},
    {state_id: 16, district_name: "Gulbarga", district_id: 267},
    {state_id: 16, district_name: "Hassan", district_id: 289},
    {state_id: 16, district_name: "Haveri", district_id: 279},
    {state_id: 16, district_name: "Kodagu", district_id: 283},
    {state_id: 16, district_name: "Kolar", district_id: 277},
    {state_id: 16, district_name: "Koppal", district_id: 282},
    {state_id: 16, district_name: "Mandya", district_id: 290},
    {state_id: 16, district_name: "Mysore", district_id: 266},
    {state_id: 16, district_name: "Raichur", district_id: 284},
    {state_id: 16, district_name: "Ramanagara", district_id: 292},
    {state_id: 16, district_name: "Shimoga", district_id: 287},
    {state_id: 16, district_name: "Tumkur", district_id: 288},
    {state_id: 16, district_name: "Udupi", district_id: 286},
    {state_id: 16, district_name: "Uttar Kannada", district_id: 281},
    {state_id: 16, district_name: "Vijayapura", district_id: 293},
    {state_id: 16, district_name: "Yadgir", district_id: 285},
    {state_id: 13, district_name: "Bilaspur", district_id: 219},
    {state_id: 13, district_name: "Chamba", district_id: 214},
    {state_id: 13, district_name: "Hamirpur", district_id: 217},
    {state_id: 13, district_name: "Kangra", district_id: 213},
    {state_id: 13, district_name: "Kinnaur", district_id: 216},
    {state_id: 13, district_name: "Kullu", district_id: 211},
    {state_id: 13, district_name: "Lahaul Spiti", district_id: 210},
    {state_id: 13, district_name: "Mandi", district_id: 215},
    {state_id: 13, district_name: "Shimla", district_id: 208},
    {state_id: 13, district_name: "Sirmaur", district_id: 212},
    {state_id: 13, district_name: "Solan", district_id: 209},
    {state_id: 13, district_name: "Una", district_id: 218},
    {state_id: 23, district_name: "East Garo Hills", district_id: 424},
    {state_id: 23, district_name: "East Jaintia Hills", district_id: 418},
    {state_id: 23, district_name: "East Khasi Hills", district_id: 414},
    {state_id: 23, district_name: "North Garo Hills", district_id: 423},
    {state_id: 23, district_name: "Ri-Bhoi", district_id: 417},
    {state_id: 23, district_name: "South Garo Hills", district_id: 421},
    {state_id: 23, district_name: "South West Garo Hills", district_id: 422},
    {state_id: 23, district_name: "South West Khasi Hills", district_id: 415},
    {state_id: 23, district_name: "West Garo Hills", district_id: 420},
    {state_id: 23, district_name: "West Jaintia Hills", district_id: 416},
    {state_id: 23, district_name: "West Khasi Hills", district_id: 419},
    {state_id: 24, district_name: "Aizawl East", district_id: 425},
    {state_id: 24, district_name: "Aizawl West", district_id: 426},
    {state_id: 24, district_name: "Champhai", district_id: 429},
    {state_id: 24, district_name: "Kolasib", district_id: 428},
    {state_id: 24, district_name: "Lawngtlai", district_id: 432},
    {state_id: 24, district_name: "Lunglei", district_id: 431},
    {state_id: 24, district_name: "Mamit", district_id: 427},
    {state_id: 24, district_name: "Serchhip", district_id: 430},
    {state_id: 24, district_name: "Siaha", district_id: 433},
    {state_id: 20, district_name: "Agar", district_id: 320},
    {state_id: 20, district_name: "Alirajpur", district_id: 357},
    {state_id: 20, district_name: "Anuppur", district_id: 334},
    {state_id: 20, district_name: "Ashoknagar", district_id: 354},
    {state_id: 20, district_name: "Balaghat", district_id: 338},
    {state_id: 20, district_name: "Barwani", district_id: 343},
    {state_id: 20, district_name: "Betul", district_id: 362},
    {state_id: 20, district_name: "Bhind", district_id: 351},
    {state_id: 20, district_name: "Bhopal", district_id: 312},
    {state_id: 20, district_name: "Burhanpur", district_id: 342},
    {state_id: 20, district_name: "Chhatarpur", district_id: 328},
    {state_id: 20, district_name: "Chhindwara", district_id: 337},
    {state_id: 20, district_name: "Damoh", district_id: 327},
    {state_id: 20, district_name: "Datia", district_id: 350},
    {state_id: 20, district_name: "Dewas", district_id: 324},
    {state_id: 20, district_name: "Dhar", district_id: 341},
    {state_id: 20, district_name: "Dindori", district_id: 336},
    {state_id: 20, district_name: "Guna", district_id: 348},
    {state_id: 20, district_name: "Gwalior", district_id: 313},
    {state_id: 20, district_name: "Harda", district_id: 361},
    {state_id: 20, district_name: "Hoshangabad", district_id: 360},
    {state_id: 20, district_name: "Indore", district_id: 314},
    {state_id: 20, district_name: "Jabalpur", district_id: 315},
    {state_id: 20, district_name: "Jhabua", district_id: 340},
    {state_id: 20, district_name: "Katni", district_id: 353},
    {state_id: 20, district_name: "Khandwa", district_id: 339},
    {state_id: 20, district_name: "Khargone", district_id: 344},
    {state_id: 20, district_name: "Mandla", district_id: 335},
    {state_id: 20, district_name: "Mandsaur", district_id: 319},
    {state_id: 20, district_name: "Morena", district_id: 347},
    {state_id: 20, district_name: "Narsinghpur", district_id: 352},
    {state_id: 20, district_name: "Neemuch", district_id: 323},
    {state_id: 20, district_name: "Panna", district_id: 326},
    {state_id: 20, district_name: "Raisen", district_id: 359},
    {state_id: 20, district_name: "Rajgarh", district_id: 358},
    {state_id: 20, district_name: "Ratlam", district_id: 322},
    {state_id: 20, district_name: "Rewa", district_id: 316},
    {state_id: 20, district_name: "Sagar", district_id: 317},
    {state_id: 20, district_name: "Satna", district_id: 333},
    {state_id: 20, district_name: "Sehore", district_id: 356},
    {state_id: 20, district_name: "Seoni", district_id: 349},
    {state_id: 20, district_name: "Shahdol", district_id: 332},
    {state_id: 20, district_name: "Shajapur", district_id: 321},
    {state_id: 20, district_name: "Sheopur", district_id: 346},
    {state_id: 20, district_name: "Shivpuri", district_id: 345},
    {state_id: 20, district_name: "Sidhi", district_id: 331},
    {state_id: 20, district_name: "Singrauli", district_id: 330},
    {state_id: 20, district_name: "Tikamgarh", district_id: 325},
    {state_id: 20, district_name: "Ujjain", district_id: 318},
    {state_id: 20, district_name: "Umaria", district_id: 329},
    {state_id: 20, district_name: "Vidisha", district_id: 355},
    {state_id: 32, district_name: "Adilabad", district_id: 582},
    {state_id: 32, district_name: "Bhadradri Kothagudem", district_id: 583},
    {state_id: 32, district_name: "Hyderabad", district_id: 581},
    {state_id: 32, district_name: "Jagtial", district_id: 584},
    {state_id: 32, district_name: "Jangaon", district_id: 585},
    {state_id: 32, district_name: "Jayashankar Bhupalpally", district_id: 586},
    {state_id: 32, district_name: "Jogulamba Gadwal", district_id: 587},
    {state_id: 32, district_name: "Kamareddy", district_id: 588},
    {state_id: 32, district_name: "Karimnagar", district_id: 589},
    {state_id: 32, district_name: "Khammam", district_id: 590},
    {state_id: 32, district_name: "Kumuram Bheem", district_id: 591},
    {state_id: 32, district_name: "Mahabubabad", district_id: 592},
    {state_id: 32, district_name: "Mahabubnagar", district_id: 593},
    {state_id: 32, district_name: "Mancherial", district_id: 594},
    {state_id: 32, district_name: "Medak", district_id: 595},
    {state_id: 32, district_name: "Medchal", district_id: 596},
    {state_id: 32, district_name: "Mulugu", district_id: 612},
    {state_id: 32, district_name: "Nagarkurnool", district_id: 597},
    {state_id: 32, district_name: "Nalgonda", district_id: 598},
    {state_id: 32, district_name: "Narayanpet", district_id: 613},
    {state_id: 32, district_name: "Nirmal", district_id: 599},
    {state_id: 32, district_name: "Nizamabad", district_id: 600},
    {state_id: 32, district_name: "Peddapalli", district_id: 601},
    {state_id: 32, district_name: "Rajanna Sircilla", district_id: 602},
    {state_id: 32, district_name: "Rangareddy", district_id: 603},
    {state_id: 32, district_name: "Sangareddy", district_id: 604},
    {state_id: 32, district_name: "Siddipet", district_id: 605},
    {state_id: 32, district_name: "Suryapet", district_id: 606},
    {state_id: 32, district_name: "Vikarabad", district_id: 607},
    {state_id: 32, district_name: "Wanaparthy", district_id: 608},
    {state_id: 32, district_name: "Warangal(Rural)", district_id: 609},
    {state_id: 32, district_name: "Warangal(Urban)", district_id: 610},
    {state_id: 32, district_name: "Yadadri Bhuvanagiri", district_id: 611},
    {state_id: 22, district_name: "Bishnupur", district_id: 398},
    {state_id: 22, district_name: "Chandel", district_id: 399},
    {state_id: 22, district_name: "Churachandpur", district_id: 400},
    {state_id: 22, district_name: "Imphal East", district_id: 401},
    {state_id: 22, district_name: "Imphal West", district_id: 402},
    {state_id: 22, district_name: "Jiribam", district_id: 410},
    {state_id: 22, district_name: "Kakching", district_id: 413},
    {state_id: 22, district_name: "Kamjong", district_id: 409},
    {state_id: 22, district_name: "Kangpokpi", district_id: 408},
    {state_id: 22, district_name: "Noney", district_id: 412},
    {state_id: 22, district_name: "Pherzawl", district_id: 411},
    {state_id: 22, district_name: "Senapati", district_id: 403},
    {state_id: 22, district_name: "Tamenglong", district_id: 404},
    {state_id: 22, district_name: "Tengnoupal", district_id: 407},
    {state_id: 22, district_name: "Thoubal", district_id: 405},
    {state_id: 22, district_name: "Ukhrul", district_id: 406},
    {state_id: 36, district_name: "Alipurduar District", district_id: 710},
    {state_id: 36, district_name: "Bankura", district_id: 711},
    {state_id: 36, district_name: "Basirhat HD (North 24 Parganas)", district_id: 712},
    {state_id: 36, district_name: "Birbhum", district_id: 713},
    {state_id: 36, district_name: "Bishnupur HD (Bankura)", district_id: 714},
    {state_id: 36, district_name: "Cooch Behar", district_id: 715},
    {state_id: 36, district_name: "COOCHBEHAR", district_id: 783},
    {state_id: 36, district_name: "Dakshin Dinajpur", district_id: 716},
    {state_id: 36, district_name: "Darjeeling", district_id: 717},
    {state_id: 36, district_name: "Diamond Harbor HD (S 24 Parganas)", district_id: 718},
    {state_id: 36, district_name: "East Bardhaman", district_id: 719},
    {state_id: 36, district_name: "Hoogly", district_id: 720},
    {state_id: 36, district_name: "Howrah", district_id: 721},
    {state_id: 36, district_name: "Jalpaiguri", district_id: 722},
    {state_id: 36, district_name: "Jhargram", district_id: 723},
    {state_id: 36, district_name: "Kalimpong", district_id: 724},
    {state_id: 36, district_name: "Kolkata", district_id: 725},
    {state_id: 36, district_name: "Malda", district_id: 726},
    {state_id: 36, district_name: "Murshidabad", district_id: 727},
    {state_id: 36, district_name: "Nadia", district_id: 728},
    {state_id: 36, district_name: "Nandigram HD (East Medinipore)", district_id: 729},
    {state_id: 36, district_name: "North 24 Parganas", district_id: 730},
    {state_id: 36, district_name: "Paschim Medinipore", district_id: 731},
    {state_id: 36, district_name: "Purba Medinipore", district_id: 732},
    {state_id: 36, district_name: "Purulia", district_id: 733},
    {state_id: 36, district_name: "Rampurhat HD (Birbhum)", district_id: 734},
    {state_id: 36, district_name: "South 24 Parganas", district_id: 735},
    {state_id: 36, district_name: "Uttar Dinajpur", district_id: 736},
    {state_id: 36, district_name: "West Bardhaman", district_id: 737},
    {state_id: 19, district_name: "Agatti Island", district_id: 796},
    {state_id: 19, district_name: "Lakshadweep", district_id: 311},
    {state_id: 31, district_name: "Aranthangi", district_id: 779},
    {state_id: 31, district_name: "Ariyalur", district_id: 555},
    {state_id: 31, district_name: "Attur", district_id: 578},
    {state_id: 31, district_name: "Chengalpet", district_id: 565},
    {state_id: 31, district_name: "Chennai", district_id: 571},
    {state_id: 31, district_name: "Cheyyar", district_id: 778},
    {state_id: 31, district_name: "Coimbatore", district_id: 539},
    {state_id: 31, district_name: "Cuddalore", district_id: 547},
    {state_id: 31, district_name: "Dharmapuri", district_id: 566},
    {state_id: 31, district_name: "Dindigul", district_id: 556},
    {state_id: 31, district_name: "Erode", district_id: 563},
    {state_id: 31, district_name: "Kallakurichi", district_id: 552},
    {state_id: 31, district_name: "Kanchipuram", district_id: 557},
    {state_id: 31, district_name: "Kanyakumari", district_id: 544},
    {state_id: 31, district_name: "Karur", district_id: 559},
    {state_id: 31, district_name: "Kovilpatti", district_id: 780},
    {state_id: 31, district_name: "Krishnagiri", district_id: 562},
    {state_id: 31, district_name: "Madurai", district_id: 540},
    {state_id: 31, district_name: "Nagapattinam", district_id: 576},
    {state_id: 31, district_name: "Namakkal", district_id: 558},
    {state_id: 31, district_name: "Nilgiris", district_id: 577},
    {state_id: 31, district_name: "Palani", district_id: 564},
    {state_id: 31, district_name: "Paramakudi", district_id: 573},
    {state_id: 31, district_name: "Perambalur", district_id: 570},
    {state_id: 31, district_name: "Poonamallee", district_id: 575},
    {state_id: 31, district_name: "Pudukkottai", district_id: 546},
    {state_id: 31, district_name: "Ramanathapuram", district_id: 567},
    {state_id: 31, district_name: "Ranipet", district_id: 781},
    {state_id: 31, district_name: "Salem", district_id: 545},
    {state_id: 31, district_name: "Sivaganga", district_id: 561},
    {state_id: 31, district_name: "Sivakasi", district_id: 580},
    {state_id: 31, district_name: "Tenkasi", district_id: 551},
    {state_id: 31, district_name: "Thanjavur", district_id: 541},
    {state_id: 31, district_name: "Theni", district_id: 569},
    {state_id: 31, district_name: "Thoothukudi (Tuticorin)", district_id: 554},
    {state_id: 31, district_name: "Tiruchirappalli", district_id: 560},
    {state_id: 31, district_name: "Tirunelveli", district_id: 548},
    {state_id: 31, district_name: "Tirupattur", district_id: 550},
    {state_id: 31, district_name: "Tiruppur", district_id: 568},
    {state_id: 31, district_name: "Tiruvallur", district_id: 572},
    {state_id: 31, district_name: "Tiruvannamalai", district_id: 553},
    {state_id: 31, district_name: "Tiruvarur", district_id: 574},
    {state_id: 31, district_name: "Vellore", district_id: 543},
    {state_id: 31, district_name: "Viluppuram", district_id: 542},
    {state_id: 31, district_name: "Virudhunagar", district_id: 549},
    {state_id: 29, district_name: "Ajmer", district_id: 507},
    {state_id: 29, district_name: "Alwar", district_id: 512},
    {state_id: 29, district_name: "Banswara", district_id: 519},
    {state_id: 29, district_name: "Baran", district_id: 516},
    {state_id: 29, district_name: "Barmer", district_id: 528},
    {state_id: 29, district_name: "Bharatpur", district_id: 508},
    {state_id: 29, district_name: "Bhilwara", district_id: 523},
    {state_id: 29, district_name: "Bikaner", district_id: 501},
    {state_id: 29, district_name: "Bundi", district_id: 514},
    {state_id: 29, district_name: "Chittorgarh", district_id: 521},
    {state_id: 29, district_name: "Churu", district_id: 530},
    {state_id: 29, district_name: "Dausa", district_id: 511},
    {state_id: 29, district_name: "Dholpur", district_id: 524},
    {state_id: 29, district_name: "Dungarpur", district_id: 520},
    {state_id: 29, district_name: "Hanumangarh", district_id: 517},
    {state_id: 29, district_name: "Jaipur I", district_id: 505},
    {state_id: 29, district_name: "Jaipur II", district_id: 506},
    {state_id: 29, district_name: "Jaisalmer", district_id: 527},
    {state_id: 29, district_name: "Jalore", district_id: 533},
    {state_id: 29, district_name: "Jhalawar", district_id: 515},
    {state_id: 29, district_name: "Jhunjhunu", district_id: 510},
    {state_id: 29, district_name: "Jodhpur", district_id: 502},
    {state_id: 29, district_name: "Karauli", district_id: 525},
    {state_id: 29, district_name: "Kota", district_id: 503},
    {state_id: 29, district_name: "Nagaur", district_id: 532},
    {state_id: 29, district_name: "Pali", district_id: 529},
    {state_id: 29, district_name: "Pratapgarh", district_id: 522},
    {state_id: 29, district_name: "Rajsamand", district_id: 518},
    {state_id: 29, district_name: "Sawai Madhopur", district_id: 534},
    {state_id: 29, district_name: "Sikar", district_id: 513},
    {state_id: 29, district_name: "Sirohi", district_id: 531},
    {state_id: 29, district_name: "Sri Ganganagar", district_id: 509},
    {state_id: 29, district_name: "Tonk", district_id: 526},
    {state_id: 29, district_name: "Udaipur", district_id: 504},
    {state_id: 26, district_name: "Angul", district_id: 445},
    {state_id: 26, district_name: "Balangir", district_id: 448},
    {state_id: 26, district_name: "Balasore", district_id: 447},
    {state_id: 26, district_name: "Bargarh", district_id: 472},
    {state_id: 26, district_name: "Bhadrak", district_id: 454},
    {state_id: 26, district_name: "Boudh", district_id: 468},
    {state_id: 26, district_name: "Cuttack", district_id: 457},
    {state_id: 26, district_name: "Deogarh", district_id: 473},
    {state_id: 26, district_name: "Dhenkanal", district_id: 458},
    {state_id: 26, district_name: "Gajapati", district_id: 467},
    {state_id: 26, district_name: "Ganjam", district_id: 449},
    {state_id: 26, district_name: "Jagatsinghpur", district_id: 459},
    {state_id: 26, district_name: "Jajpur", district_id: 460},
    {state_id: 26, district_name: "Jharsuguda", district_id: 474},
    {state_id: 26, district_name: "Kalahandi", district_id: 464},
    {state_id: 26, district_name: "Kandhamal", district_id: 450},
    {state_id: 26, district_name: "Kendrapara", district_id: 461},
    {state_id: 26, district_name: "Kendujhar", district_id: 455},
    {state_id: 26, district_name: "Khurda", district_id: 446},
    {state_id: 26, district_name: "Koraput", district_id: 451},
    {state_id: 26, district_name: "Malkangiri", district_id: 469},
    {state_id: 26, district_name: "Mayurbhanj", district_id: 456},
    {state_id: 26, district_name: "Nabarangpur", district_id: 470},
    {state_id: 26, district_name: "Nayagarh", district_id: 462},
    {state_id: 26, district_name: "Nuapada", district_id: 465},
    {state_id: 26, district_name: "Puri", district_id: 463},
    {state_id: 26, district_name: "Rayagada", district_id: 471},
    {state_id: 26, district_name: "Sambalpur", district_id: 452},
    {state_id: 26, district_name: "Subarnapur", district_id: 466},
    {state_id: 26, district_name: "Sundargarh", district_id: 453},
    {state_id: 34, district_name: "Agra", district_id: 622},
    {state_id: 34, district_name: "Aligarh", district_id: 623},
    {state_id: 34, district_name: "Ambedkar Nagar", district_id: 625},
    {state_id: 34, district_name: "Amethi", district_id: 626},
    {state_id: 34, district_name: "Amroha", district_id: 627},
    {state_id: 34, district_name: "Auraiya", district_id: 628},
    {state_id: 34, district_name: "Ayodhya", district_id: 646},
    {state_id: 34, district_name: "Azamgarh", district_id: 629},
    {state_id: 34, district_name: "Badaun", district_id: 630},
    {state_id: 34, district_name: "Baghpat", district_id: 631},
    {state_id: 34, district_name: "Bahraich", district_id: 632},
    {state_id: 34, district_name: "Balarampur", district_id: 633},
    {state_id: 34, district_name: "Ballia", district_id: 634},
    {state_id: 34, district_name: "Banda", district_id: 635},
    {state_id: 34, district_name: "Barabanki", district_id: 636},
    {state_id: 34, district_name: "Bareilly", district_id: 637},
    {state_id: 34, district_name: "Basti", district_id: 638},
    {state_id: 34, district_name: "Bhadohi", district_id: 687},
    {state_id: 34, district_name: "Bijnour", district_id: 639},
    {state_id: 34, district_name: "Bulandshahr", district_id: 640},
    {state_id: 34, district_name: "Chandauli", district_id: 641},
    {state_id: 34, district_name: "Chitrakoot", district_id: 642},
    {state_id: 34, district_name: "Deoria", district_id: 643},
    {state_id: 34, district_name: "Etah", district_id: 644},
    {state_id: 34, district_name: "Etawah", district_id: 645},
    {state_id: 34, district_name: "Farrukhabad", district_id: 647},
    {state_id: 34, district_name: "Fatehpur", district_id: 648},
    {state_id: 34, district_name: "Firozabad", district_id: 649},
    {state_id: 34, district_name: "Gautam Buddha Nagar", district_id: 650},
    {state_id: 34, district_name: "Ghaziabad", district_id: 651},
    {state_id: 34, district_name: "Ghazipur", district_id: 652},
    {state_id: 34, district_name: "Gonda", district_id: 653},
    {state_id: 34, district_name: "Gorakhpur", district_id: 654},
    {state_id: 34, district_name: "Hamirpur", district_id: 655},
    {state_id: 34, district_name: "Hapur", district_id: 656},
    {state_id: 34, district_name: "Hardoi", district_id: 657},
    {state_id: 34, district_name: "Hathras", district_id: 658},
    {state_id: 34, district_name: "Jalaun", district_id: 659},
    {state_id: 34, district_name: "Jaunpur", district_id: 660},
    {state_id: 34, district_name: "Jhansi", district_id: 661},
    {state_id: 34, district_name: "Kannauj", district_id: 662},
    {state_id: 34, district_name: "Kanpur Dehat", district_id: 663},
    {state_id: 34, district_name: "Kanpur Nagar", district_id: 664},
    {state_id: 34, district_name: "Kasganj", district_id: 665},
    {state_id: 34, district_name: "Kaushambi", district_id: 666},
    {state_id: 34, district_name: "Kushinagar", district_id: 667},
    {state_id: 34, district_name: "Lakhimpur Kheri", district_id: 668},
    {state_id: 34, district_name: "Lalitpur", district_id: 669},
    {state_id: 34, district_name: "Lucknow", district_id: 670},
    {state_id: 34, district_name: "Maharajganj", district_id: 671},
    {state_id: 34, district_name: "Mahoba", district_id: 672},
    {state_id: 34, district_name: "Mainpuri", district_id: 673},
    {state_id: 34, district_name: "Mathura", district_id: 674},
    {state_id: 34, district_name: "Mau", district_id: 675},
    {state_id: 34, district_name: "Meerut", district_id: 676},
    {state_id: 34, district_name: "Mirzapur", district_id: 677},
    {state_id: 34, district_name: "Moradabad", district_id: 678},
    {state_id: 34, district_name: "Muzaffarnagar", district_id: 679},
    {state_id: 34, district_name: "Pilibhit", district_id: 680},
    {state_id: 34, district_name: "Pratapgarh", district_id: 682},
    {state_id: 34, district_name: "Prayagraj", district_id: 624},
    {state_id: 34, district_name: "Raebareli", district_id: 681},
    {state_id: 34, district_name: "Rampur", district_id: 683},
    {state_id: 34, district_name: "Saharanpur", district_id: 684},
    {state_id: 34, district_name: "Sambhal", district_id: 685},
    {state_id: 34, district_name: "Sant Kabir Nagar", district_id: 686},
    {state_id: 34, district_name: "Shahjahanpur", district_id: 688},
    {state_id: 34, district_name: "Shamli", district_id: 689},
    {state_id: 34, district_name: "Shravasti", district_id: 690},
    {state_id: 34, district_name: "Siddharthnagar", district_id: 691},
    {state_id: 34, district_name: "Sitapur", district_id: 692},
    {state_id: 34, district_name: "Sonbhadra", district_id: 693},
    {state_id: 34, district_name: "Sultanpur", district_id: 694},
    {state_id: 34, district_name: "Unnao", district_id: 695},
    {state_id: 34, district_name: "Varanasi", district_id: 696},
    {state_id: 25, district_name: "Dimapur", district_id: 434},
    {state_id: 25, district_name: "Kiphire", district_id: 444},
    {state_id: 25, district_name: "Kohima", district_id: 441},
    {state_id: 25, district_name: "Longleng", district_id: 438},
    {state_id: 25, district_name: "Mokokchung", district_id: 437},
    {state_id: 25, district_name: "Mon", district_id: 439},
    {state_id: 25, district_name: "Peren", district_id: 435},
    {state_id: 25, district_name: "Phek", district_id: 443},
    {state_id: 25, district_name: "Tuensang", district_id: 440},
    {state_id: 25, district_name: "Wokha", district_id: 436},
    {state_id: 25, district_name: "Zunheboto", district_id: 442},
    {state_id: 27, district_name: "Karaikal", district_id: 476},
    {state_id: 27, district_name: "Mahe", district_id: 477},
    {state_id: 27, district_name: "Puducherry", district_id: 475},
    {state_id: 27, district_name: "Yanam", district_id: 478},
    {state_id: 21, district_name: "Ahmednagar", district_id: 391},
    {state_id: 21, district_name: "Akola", district_id: 364},
    {state_id: 21, district_name: "Amravati", district_id: 366},
    {state_id: 21, district_name: "Aurangabad ", district_id: 397},
    {state_id: 21, district_name: "Beed", district_id: 384},
    {state_id: 21, district_name: "Bhandara", district_id: 370},
    {state_id: 21, district_name: "Buldhana", district_id: 367},
    {state_id: 21, district_name: "Chandrapur", district_id: 380},
    {state_id: 21, district_name: "Dhule", district_id: 388},
    {state_id: 21, district_name: "Gadchiroli", district_id: 379},
    {state_id: 21, district_name: "Gondia", district_id: 378},
    {state_id: 21, district_name: "Hingoli", district_id: 386},
    {state_id: 21, district_name: "Jalgaon", district_id: 390},
    {state_id: 21, district_name: "Jalna", district_id: 396},
    {state_id: 21, district_name: "Kolhapur", district_id: 371},
    {state_id: 21, district_name: "Latur", district_id: 383},
    {state_id: 21, district_name: "Mumbai", district_id: 395},
    {state_id: 21, district_name: "Nagpur", district_id: 365},
    {state_id: 21, district_name: "Nanded", district_id: 382},
    {state_id: 21, district_name: "Nandurbar", district_id: 387},
    {state_id: 21, district_name: "Nashik", district_id: 389},
    {state_id: 21, district_name: "Osmanabad", district_id: 381},
    {state_id: 21, district_name: "Palghar", district_id: 394},
    {state_id: 21, district_name: "Parbhani", district_id: 385},
    {state_id: 21, district_name: "Pune", district_id: 363},
    {state_id: 21, district_name: "Raigad", district_id: 393},
    {state_id: 21, district_name: "Ratnagiri", district_id: 372},
    {state_id: 21, district_name: "Sangli", district_id: 373},
    {state_id: 21, district_name: "Satara", district_id: 376},
    {state_id: 21, district_name: "Sindhudurg", district_id: 374},
    {state_id: 21, district_name: "Solapur", district_id: 375},
    {state_id: 21, district_name: "Thane", district_id: 392},
    {state_id: 21, district_name: "Wardha", district_id: 377},
    {state_id: 21, district_name: "Washim", district_id: 369},
    {state_id: 21, district_name: "Yavatmal", district_id: 368},
    {state_id: 33, district_name: "Dhalai", district_id: 614},
    {state_id: 33, district_name: "Gomati", district_id: 615},
    {state_id: 33, district_name: "Khowai", district_id: 616},
    {state_id: 33, district_name: "North Tripura", district_id: 617},
    {state_id: 33, district_name: "Sepahijala", district_id: 618},
    {state_id: 33, district_name: "South Tripura", district_id: 619},
    {state_id: 33, district_name: "Unakoti", district_id: 620},
    {state_id: 33, district_name: "West Tripura", district_id: 621},
    {state_id: 28, district_name: "Amritsar", district_id: 485},
    {state_id: 28, district_name: "Barnala", district_id: 483},
    {state_id: 28, district_name: "Bathinda", district_id: 493},
    {state_id: 28, district_name: "Faridkot", district_id: 499},
    {state_id: 28, district_name: "Fatehgarh Sahib", district_id: 484},
    {state_id: 28, district_name: "Fazilka", district_id: 487},
    {state_id: 28, district_name: "Ferozpur", district_id: 480},
    {state_id: 28, district_name: "Gurdaspur", district_id: 489},
    {state_id: 28, district_name: "Hoshiarpur", district_id: 481},
    {state_id: 28, district_name: "Jalandhar", district_id: 492},
    {state_id: 28, district_name: "Kapurthala", district_id: 479},
    {state_id: 28, district_name: "Ludhiana", district_id: 488},
    {state_id: 28, district_name: "Mansa", district_id: 482},
    {state_id: 28, district_name: "Moga", district_id: 491},
    {state_id: 28, district_name: "Pathankot", district_id: 486},
    {state_id: 28, district_name: "Patiala", district_id: 494},
    {state_id: 28, district_name: "Rup Nagar", district_id: 497},
    {state_id: 28, district_name: "Sangrur", district_id: 498},
    {state_id: 28, district_name: "SAS Nagar", district_id: 496},
    {state_id: 28, district_name: "SBS Nagar", district_id: 500},
    {state_id: 28, district_name: "Sri Muktsar Sahib", district_id: 490},
    {state_id: 28, district_name: "Tarn Taran", district_id: 495},
    {state_id: 35, district_name: "Almora", district_id: 704},
    {state_id: 35, district_name: "Bageshwar", district_id: 707},
    {state_id: 35, district_name: "Chamoli", district_id: 699},
    {state_id: 35, district_name: "Champawat", district_id: 708},
    {state_id: 35, district_name: "Dehradun", district_id: 697},
    {state_id: 35, district_name: "Haridwar", district_id: 702},
    {state_id: 35, district_name: "Nainital", district_id: 709},
    {state_id: 35, district_name: "Pauri Garhwal", district_id: 698},
    {state_id: 35, district_name: "Pithoragarh", district_id: 706},
    {state_id: 35, district_name: "Rudraprayag", district_id: 700},
    {state_id: 35, district_name: "Tehri Garhwal", district_id: 701},
    {state_id: 35, district_name: "Udham Singh Nagar", district_id: 705},
    {state_id: 35, district_name: "Uttarkashi", district_id: 703},
    {state_id: 14, district_name: "Anantnag", district_id: 224},
    {state_id: 14, district_name: "Bandipore", district_id: 223},
    {state_id: 14, district_name: "Baramulla", district_id: 225},
    {state_id: 14, district_name: "Budgam", district_id: 229},
    {state_id: 14, district_name: "Doda", district_id: 232},
    {state_id: 14, district_name: "Ganderbal", district_id: 228},
    {state_id: 14, district_name: "Jammu", district_id: 230},
    {state_id: 14, district_name: "Kathua", district_id: 234},
    {state_id: 14, district_name: "Kishtwar", district_id: 231},
    {state_id: 14, district_name: "Kulgam", district_id: 221},
    {state_id: 14, district_name: "Kupwara", district_id: 226},
    {state_id: 14, district_name: "Poonch", district_id: 238},
    {state_id: 14, district_name: "Pulwama", district_id: 227},
    {state_id: 14, district_name: "Rajouri", district_id: 237},
    {state_id: 14, district_name: "Ramban", district_id: 235},
    {state_id: 14, district_name: "Reasi", district_id: 239},
    {state_id: 14, district_name: "Samba", district_id: 236},
    {state_id: 14, district_name: "Shopian", district_id: 222},
    {state_id: 14, district_name: "Srinagar", district_id: 220},
    {state_id: 14, district_name: "Udhampur", district_id: 233},
    {state_id: 17, district_name: "Alappuzha", district_id: 301},
    {state_id: 17, district_name: "Ernakulam", district_id: 307},
    {state_id: 17, district_name: "Idukki", district_id: 306},
    {state_id: 17, district_name: "Kannur", district_id: 297},
    {state_id: 17, district_name: "Kasaragod", district_id: 295},
    {state_id: 17, district_name: "Kollam", district_id: 298},
    {state_id: 17, district_name: "Kottayam", district_id: 304},
    {state_id: 17, district_name: "Kozhikode", district_id: 305},
    {state_id: 17, district_name: "Malappuram", district_id: 302},
    {state_id: 17, district_name: "Palakkad", district_id: 308},
    {state_id: 17, district_name: "Pathanamthitta", district_id: 300},
    {state_id: 17, district_name: "Thiruvananthapuram", district_id: 296},
    {state_id: 17, district_name: "Thrissur", district_id: 303},
    {state_id: 17, district_name: "Wayanad", district_id: 299},
    {state_id: 30, district_name: "East Sikkim", district_id: 535},
    {state_id: 30, district_name: "North Sikkim", district_id: 537},
    {state_id: 30, district_name: "South Sikkim", district_id: 538},
    {state_id: 30, district_name: "West Sikkim", district_id: 536}
]